[colors]

grisardoise = #373B41
grischarbon = #2e3436
white = #ffffff
noir = #000000
anthracite = #282A36
grisfonce = #CC282A36
grismoyen = #c0bfbc
bleuvert = #8abeb7
alert ="#CC5500"
grisfer = #707880
beigepur = #99F5F5DC
blancivoire = #99FFFFF0
blancantique = #99FAEBD7
saumonclairopaque = #FFA07A
saumonclair = #99FFA07A
saumonrose	= #99FF8C69
pechedoux	= #99FFDAB9
background = ${colors.saumonclairopaque}
foreground = ${colors.grisfer}

[bar/ma_barre]
; --- POSITIONNEMENT ---
; monitor = ${env:MONITOR:}
bottom = true
width = 100%
height = 26
fixed-center = true
enable-ipc = true
pseudo-transparency = true

; --- COMPORTEMENT ---
; 1. Permet à Openbox de gérer la barre comme un Dock (libère les boutons)
override-redirect = false
; 2. Indique explicitement à quel gestionnaire de fenêtres s'adapter
; incompatible  wm-restack = openbox
;wm-restack = openbox
; 3. Supprime la zone "morte" qui bloque souvent les clics au bord de l'écran
padding-top = 0
padding-bottom = 0
wm-name = polybar-barre
locale = fr_FR.UTF-8

; --- APPARENCE ---
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 2
padding-left = 1
padding-right = 1
module-margin = 1

; --- POLICES ---
font-0 = "sans-serif:size=10;0"
font-1 = "Symbols Nerd Font:size=12;2"
; La petite police pour la date
font-2 = "sans-serif:size=8;-4"  
font-3 = "sans-serif:size=10;10"  


; --- MODULES ---
modules-left = applicationsmenu xworkspaces fav-terminal fav-thunar show-desktop
modules-center = xwindow tasklist
; Ici, on place le systray juste avant help-center (?), date et powermenu
modules-right = cpu ram temp netspeed systemlog systray printer help-center kdb-advanced date powermenu 

; --- CONFIGURATION DU MODULE SYSTRAY ---
[module/systray]
type = internal/tray
tray-spacing = 8pt
tray-padding = 2px
tray-size = 16

[module/xworkspaces]
type = internal/xworkspaces

icon-0 = 1: Terminal;󰣆
icon-1 = 2: Bureau;󰣆

pin-workspaces = false
enable-click = true
enable-scroll = true
reverse-scroll = true

label-active = %icon%
label-active-background = #3b719f
label-active-foreground = #ffffff
label-active-overline = ${colors.noir}
label-active-padding = 2

label-occupied = %icon%
label-occupied-foreground = ${colors.noir}
label-occupied-underline = ${colors.noir}
label-occupied-padding = 2

label-urgent = %icon%
label-urgent-background = #ba2922
label-urgent-foreground = #ffffff
label-urgent-padding = 2

label-empty = %icon%
label-empty-foreground = ${colors.grisfer}
label-empty-padding = 2

[module/sep]
type = custom/text
format = " "
format-foreground = ${colors.grisfer}
format-padding = 1

[module/xwindow]
type = internal/xwindow
format = <label>
label = %title%
label-maxlen = 40
label-empty = " 󰣇 Arch Linux "
label-empty-foreground = ${colors.grisfer}

[module/show-desktop]
type = custom/script
; Icône de bureau (Nerd Font). Vous pouvez la changer par 󰇄 ou 󰖯
exec = echo "󰇄 "
interval = 1

; Commande pour minimiser/restaurer toutes les fenêtres
click-left = wmctrl -k on
click-right = wmctrl -k off

; Style optionnel
format-foreground = ${colors.noir}
format-padding = 1

[module/tasklist]
type = custom/script
exec = /usr/local/bin/tasklist
interval = 0.5
format = <label>
label = %output%
label-font = 2

[module/applicationsmenu]
type = custom/text
format = " 󰣇 "
format-foreground = ${colors.noir}
click-left = /usr/bin/jgmenu
click-right = /usr/bin/jgmenu

[module/fav-terminal]
type = custom/text
format = "  "
format-foreground = ${colors.noir}
# Syntaxe : script "Classe_du_programme" "commande_de_lancement"
#click-left = ~/.config/openbox/scripts/toggle_app.sh "Lxterminal" "lxterminal"
click-left = /usr/local/bin/launcher-qterminal
click-right = /usr/local/bin/launcher-qterminal

[module/fav-thunar]
type = custom/text
format = " 󰉋 "
format-foreground = ${colors.noir}
click-left = ~/.config/openbox/scripts/toggle_app.sh "Thunar" "thunar"

[module/cpu]
type = custom/script
exec = /usr/local/bin/cpu-tool
interval = 2
format-foreground = ${colors.noir}

[module/temp]
type = custom/script
exec = /usr/local/bin/temp-tool
interval = 2
format-foreground = ${colors.noir}

[module/ram]
type = custom/script
exec = /usr/local/bin/ram-tool
interval = 5
format-foreground = ${colors.noir}
click-right = /usr/local/bin//am_monitor
click-left = /usr/local/bin/ram_monitor

[module/netspeed]
type = custom/script
exec = /usr/local/bin/net-tool
interval = 1
click-right = /usr/local/bin/net-doctor
click-left = /usr/local/bin/net-doctor

[module/kdb-advanced]
type = custom/script
exec = /usr/local/bin/kbd_status
interval = 1

# CLIC GAUCHE ou DROIT : Lance les réglages
click-left = /usr/local/bin//kb-layout
click-right = /usr/local/bin/kb-layout

[module/systemlog]
type = custom/text
format = 󰄫 
format-foreground = ${colors.noir}
click-left = /usr/local/bin/syslog_report
click-right = /usr/local/bin/syslog_report

[module/printer]
type = custom/text
format = " 󰐪 "
format-foreground = ${colors.noir}
click-left = system-config-printer

[module/date]
type = custom/script
exec = /usr/local/bin/polybar_date
interval = 5
format-background = ${colors.background}
format-foreground = ${colors.noir}
; On s'assure qu'aucune bordure ou soulignement ne gêne
format-underline =
click-left = /usr/local/bin/selectDate_libcb
click-right = /usr/local/bin/selectDate_libcb

[module/help-center]
type = custom/text
format = "  "
format-foreground = ${colors.noir}
click-left = /usr/local/bin/help_center
click-right = /usr/local/bin/help_center

[module/powermenu]
type = custom/text
format = "       "
; Force le module à toujours occuper l'espace de 10 caractères
label-width = 20
label-alignment = center
label-background = #333
format-foreground = ${colors.alert}
click-left = /usr/local/bin/powermenu
click-right = /usr/local/bin/powermenu